spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
  h2:
    console:
      enabled: true           # H2 콘솔 활성화
      path: /h2-console       # H2 콘솔 경로 설정

oauth:
  base-uri: http://localhost:8080
  redirect-uri: http://localhost:8080/oauth2/authorization/

jwt:
  access-token-expire-duration: 1000 * 60 * 30L  # 30분
  refresh-token-expire-duration: 1000 * 60 * 60 * 24L  # 24시간
  access-token-cookie-name: access_token
  refresh-token-cookie-name: access_token
  secret: cadb72b2d9a3e82e47c47f5ac779a3e828f7bb286bc08sfdw20b91f81418581dkwd920a6d2026f481a6d2sadkiu3r02aa5f49a3e82eb91f8
